### ISSUE TITLE
Fixes and additions

### ISSUE THREAD

**Issue by gtrxAC** [hstsethi/awesome-j2me#4]
- Add note that a modified version of NNJSON can be used with CLDC 1.0, see [Discord J2ME source](https://github.com/gtrxAC/discord-j2me/tree/main/src/cc/nnproject/json)
- Add [this archive.org collection](https://archive.org/details/96x65pixels_j2me) to the video games section (huge filtered/sorted collection of software, mainly games, from various sources)
- Add [this collection of emulators for J2ME](https://archive.org/details/j2me-emuSoftware) to the apps section
- Fix J2ME Fandom Wiki link (should not have www.)
- Remove mention of GBA from MeBoy emulator, as it does not support GBA.

**Comment by hstsethi** [comment]
Thank you so much. I will work on these issues.

edit: I have fixed these issues, so I am closing this issue. Feel free to comment again or open a new issue if required.
